In [ ]:
n=int(input("Ingrese la longitud del vector: "))
i=0
a=[]
b=[]
#r=[]
while i<n:
  x=int(input("Ingrese el valor a añadir en el primer vector "))
  y=int(input("Ingrese el valor a añador ene el segundo vector "))
  b.append(y)
  a.append(x)
  i=i+1
print(a)
print(b)

#producto escalar
r=0
for i in range(n):
  r += a[i] * b[i]
print(r)

Ingrese la longitud del vector: 3
Ingrese el valor a añadir en el primer vector 5
Ingrese el valor a añador ene el segundo vector 4
Ingrese el valor a añadir en el primer vector 6
Ingrese el valor a añador ene el segundo vector 7
Ingrese el valor a añadir en el primer vector 8
Ingrese el valor a añador ene el segundo vector 9
[5, 6, 8]
[4, 7, 9]
134


In [12]:
import numpy as np


filas_A = int(input("Ingrese el número de filas de la matriz A: "))
columnas_A = int(input("Ingrese el número de columnas de la matriz A: "))
filas_B = int(input("Ingrese el número de filas de la matriz B: "))
columnas_B = int(input("Ingrese el número de columnas de la matriz B: "))


if columnas_A != filas_B:
    print("No se pueden multiplicar las matrices A y B")
    exit()


print("Ingrese los elementos de la matriz A:")
A = np.zeros((filas_A, columnas_A))
for i in range(filas_A):
    for j in range(columnas_A):
        A[i][j] = int(input("Elemento ({},{}) de A: ".format(i+1, j+1)))

print("Ingrese los elementos de la matriz B:")
B = np.zeros((filas_B, columnas_B))
for i in range(filas_B):
    for j in range(columnas_B):
        B[i][j] = int(input("Elemento ({},{}) de B: ".format(i+1, j+1)))


C = 3*A
D = 4*B

try:
    E = A + B
except:
    E=["No se puede relizar"]


try:
    F = np.dot(B, A)
except:
    F=["No se puede relizar"]


print("3A:")
print(C)
print("4B:")
print(D)
print("A + B:")
print(E)
print("B x A:")
print(F)

Ingrese el número de filas de la matriz A: 3
Ingrese el número de columnas de la matriz A: 4
Ingrese el número de filas de la matriz B: 2
Ingrese el número de columnas de la matriz B: 3
No se pueden multiplicar las matrices A y B
Ingrese los elementos de la matriz A:
Elemento (1,1) de A: 4
Elemento (1,2) de A: 5
Elemento (1,3) de A: 6
Elemento (1,4) de A: 8
Elemento (2,1) de A: 7
Elemento (2,2) de A: 9
Elemento (2,3) de A: 4
Elemento (2,4) de A: 1
Elemento (3,1) de A: 2
Elemento (3,2) de A: 5
Elemento (3,3) de A: 7
Elemento (3,4) de A: 9
Ingrese los elementos de la matriz B:
Elemento (1,1) de B: 3
Elemento (1,2) de B: 1
Elemento (1,3) de B: 5
Elemento (2,1) de B: 8
Elemento (2,2) de B: 9
Elemento (2,3) de B: 7
3A:
[[12. 15. 18. 24.]
 [21. 27. 12.  3.]
 [ 6. 15. 21. 27.]]
4B:
[[12.  4. 20.]
 [32. 36. 28.]]
A + B:
['No se puede relizar']
B x A:
[[ 29.  49.  57.  70.]
 [109. 156. 133. 136.]]
